theme: jekyll-theme-primer
title: Recommender System
description: Keeping Italian Olives Pure!
baseurl:
markdown: kramdown
kramdown:
    math_engine: mathjax
    input: GFM
    syntax_highlighter: rouge
